environment: Staging
user: k8s/user

label:
  name: hello 

container:
  name: helloapp 
  pullPolicy: IfNotPresent 
  image: 332679337602.dkr.ecr.ap-east-1.amazonaws.com/hello 
  tag: v1
  port: 80
replicas: 2

service:
  port: 8080 
  type: ClusterIP
